package com.myspace.document_processing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Document implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String type;

	private java.lang.String status;

	private java.lang.String classification;

	public Document() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getClassification() {
		return this.classification;
	}

	public void setClassification(java.lang.String classification) {
		this.classification = classification;
	}
	
	public Document(java.lang.String name, java.lang.String type,
			java.lang.String status, java.lang.String classification) {
		this.name = name;
		this.type = type;
		this.status = status;
		this.classification = classification;
	}
	
	
    @Override
	public String toString() {
		return "Document [name=" + name + ", type=" + type + ", status=" + status + ", classification=" + classification + "]";
	}
}