package com.myspace.document_processing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Error implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String description;

	public Error() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public Error(java.lang.String description) {
		this.description = description;
	}

}